### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/covid_reddit_behaviour#46]
**3. Project proposal: reasoning**

Comments
This is a great project. I like it, but this is sort of only a descriptive analysis. Even though it is descriptive, I believe there can be a lot to learn here and many implications and conclusions you guys can come up with in terms of looking at trends.

5. Exploratory data analysis in a literate code document: VIZ

Comments
Well done, but I can see some extra cells that aren't working in some of the EDA pages.
In the future, it would be great to get a one-graph comparison for before and after and trends as well, as it is pretty tricky at this stage to compare the analysis between the measures/categories.

**Comment by mel-liow** [comment]
Thanks Andy for your feedback! 
We'll look to address these - i've tagged the team so that we can continue some discussions here.

**Comment by LukeAC** [comment]
Hey Andy, thanks for the feedback.

Quick question about the underlying project question being 'descriptive'. A quick lookup on definition shows:
>Descriptive statistics summarize the characteristics of a data set. Inferential statistics allow you to test a hypothesis or assess whether your data is generalizable to the broader population.

We are not summarizing characteristics of our dataset here; we are testing the hypothesis that the number of explicit references to substance use before/'after' (ahah) covid is different. Is it just that this is not properly communicated in the way the project question is phrased? I'll include the question below for ease of reference.

> Has frequency of explicit description of substance abuse in mental-health-oriented subreddits changed over the time period of 2018 through 2020?

**Comment by andytai7** [comment]
Hi @LukeAC, I think this project is very well done. I believe that maybe phrasing it differently where you can have a null hypothesis, and a hypothesis, that would work in your favour!

**Comment by MaeveShi** [comment]
Hi Andy, appreciate the feedback!

A quick question regards to the EDA part: to compare the before and after trends, shall we add a summary to briefly explain the details and the conclusion? 

Since we carried out EDA on 15 subreddit csv respectively, the summary would be from a global level or just for each subreddit(1 or 15?)

**Comment by andytai7** [comment]
Hi @MaeveShi, I would suggest having one global level table comparing the frequency before and after covid. Is there a way to combine the tables?

I would also suggest adding a brief summary explaining the details and the conclusion from a global level.

**Comment by MaeveShi** [comment]
Hi Andy @andytai7, thanks for the suggestions! I've combined the tables and also created a ipynb file including frequency plots and a brief summary on a global level!

> but I can see some extra cells that aren't working in some of the EDA pages.

For the eda pages that not working, can you take a screenshot of them since I cannot find any cells in the eda pages that's not working...Do you mean the files in the main branch of eda/subreddit?

**Comment by andytai7** [comment]
Hi @MaeveShi 

For the addictions EDA, here is the screenshot. 
<img width="1478" alt="Screen Shot 2021-12-04 at 9 12 36 PM" src="https://user-images.githubusercontent.com/45893111/144734588-ba3fe6a4-055f-45d2-9987-d7a39123d087.png">
